In [29]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [47]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

temp = torch.ones(2,3)
temp

0.00187850
CPU times: total: 0 ns
Wall time: 3.37 ms


tensor([[1., 1., 1.],
        [1., 1., 1.]])

using the time library to record execution time
%%time to record the time taken for the cell to execute

In [31]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.28447795
0.17150688


In [50]:
# embeddings, torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the examples of functions/methods with pytorch docs)


# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)


tensor([1, 2, 0, 2, 2, 2, 1, 0, 2, 2])


In [33]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [34]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [35]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [36]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [37]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [38]:
input = torch.zeros(2, 3, 4)
out1 = input.transpose(0, 1)
out2 = input.transpose(-2,-1)
print(out1.shape)
print(out2.shape)
# torch.permute works the same but you provide the new order of dimensions instead of the dimensions you'd like to swap.

torch.Size([3, 2, 4])
torch.Size([2, 4, 3])


In [39]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [40]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-0.0409,  5.6025, -8.6395], grad_fn=<SqueezeBackward4>)


In [41]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [42]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 6), where 4 is the number of inputs
# and 6 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)


torch.Size([4, 6])
tensor([[-0.3655,  0.0534,  0.0515, -1.7373,  2.3227, -0.8812],
        [ 1.2828,  0.5326, -1.1410,  0.0150, -0.4516, -0.7361],
        [-0.4217,  0.1935,  0.4434, -1.1368, -1.3438, -0.7928],
        [-0.3913, -1.1429,  0.2978, -0.5168,  1.4366,  1.2273]],
       grad_fn=<EmbeddingBackward0>)


In [43]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
# print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [44]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64
float_32 = torch.rand(2,3)
#type float32
# print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [45]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
# print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [46]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
# print(input)
print(output[:, -1, :])

tensor([[0.7554, 0.4223, 0.9233, 0.8897, 0.6459, 0.8366, 0.1255, 0.2126, 0.2373,
         0.2359],
        [0.8148, 0.0262, 0.3651, 0.0340, 0.8574, 0.1852, 0.4175, 0.4554, 0.0038,
         0.1671],
        [0.8099, 0.7192, 0.3690, 0.5457, 0.1857, 0.9525, 0.4349, 0.8529, 0.4250,
         0.9129],
        [0.8971, 0.5868, 0.8714, 0.7658, 0.5696, 0.9312, 0.7600, 0.5722, 0.4599,
         0.2881],
        [0.8935, 0.6017, 0.5578, 0.5163, 0.0684, 0.6818, 0.1124, 0.7242, 0.0565,
         0.9311],
        [0.4957, 0.1938, 0.5836, 0.3097, 0.9191, 0.3361, 0.8997, 0.2018, 0.7888,
         0.9366],
        [0.2340, 0.1934, 0.4269, 0.5622, 0.7998, 0.9278, 0.5096, 0.0094, 0.7227,
         0.3767],
        [0.9728, 0.4677, 0.7154, 0.4308, 0.4471, 0.3939, 0.9669, 0.9366, 0.0309,
         0.4395],
        [0.7712, 0.2348, 0.6565, 0.7910, 0.7035, 0.8414, 0.8604, 0.1256, 0.2580,
         0.6827],
        [0.5043, 0.1528, 0.6577, 0.4026, 0.1022, 0.3352, 0.4123, 0.3777, 0.7095,
         0.3421],
        [0

IndexError: too many indices for tensor of dimension 2

In [48]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])
